debug: true

server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost/locker
        username: root
        password:
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        database: mysql
    jackson:
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
