debug: true

server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost/locker?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password:
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        database: mysql
    jackson:
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
        date-format: yyyy-MM-dd HH:mm:ss
jiejing:
    boxSizeCode: box_size
    infoTypeCode: Info_type